spring.datasource.url=jdbc:postgresql://localhost:5432/proof_of_work
spring.datasource.username=postgres
spring.datasource.password=Utkarsh@788

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080